deco-sites/cristaistavares

components/ui/SectionDescription.tsx, components/ui/SuggestionBanners.tsx, sections/Content/SectionDescription.tsx, sections/Content/SuggestionBanners.tsx
Esta solicitação de pull adiciona novos recursos ao projeto, incluindo banners de sugestão na seção "SuggestionBanners" e descrições detalhadas na seção "SectionDescription". Esses recursos são projetados para melhorar a experiência do usuário e fornecer informações mais claras sobre o conteúdo da aplicação.
Nesta seção, foram adicionados banners de sugestão para direcionar a atenção dos usuários para informações importantes e ações que podem tomar. Os banners foram implementados usando HTML e TailwindCSS para garantir uma exibição consistente em diferentes navegadores e dispositivos.
Na seção "SectionDescription", foram adicionadas descrições detalhadas sobre o site.
=> Feat: Create Section SuggestionBanners And Section SectionDescription

components/ui/AvaliationSection.tsx, sections/Content/AvaliationSection.tsx
**Descrição das Alterações:**
Neste Pull Request, eu adicionei uma nova seção chamada "AvaliationSection" ao projeto. Essa seção permitirá que os usuários vejam avaliações de algum conteúdo ou produto e também deixem suas próprias avaliações. Isso pode ser útil para melhorar o envolvimento do usuário e coletar feedback valioso. 
Caminho da Section: $store/components/ui/AvaliationSection.tsx".
=> Feat (AvaliationSection): Review Page Created

components/product/ProductDetails.tsx, components/ui/CTA.tsx
=> Feat: Created CTA

components/header/CampaignTimer.tsx, sections/Header/CampaignTimer.tsx
=> Feat: Added Section CampaignTimer

components/ui/InstitutionalCard.tsx, sections/Institutional/InstitutionalSection.tsx
=> Feat: InstitutionalCard in Page 'Quem Somos'

sections/Institutional/InstitutionalSection.tsx
=> Fix: Alter Code

components/ui/GridImage.tsx, sections/Institutional/InstitutionalSection.tsx
=> Refactor: Adjustment Code

components/header/CampaignTimer.tsx, components/product/ProductCard.tsx, components/product/ProductMatch.tsx, components/product/ProductShelf.tsx, components/product/SkuSelector.tsx, fresh.gen.ts, islands/ProductCard.tsx
This PR removes the Product Card from an island in order to improve the site's performance.
=> New improvements

components/product/ProductCard.tsx
=> Style: Changing the Colors of the Stars

components/search/SearchResult.tsx
=> Refactor: Adjustment in Section SearchResult

.github/workflows/deco-deploy.yaml, components/Analytics.tsx, components/product/ProductShelf.tsx, deno.json, dev.ts, fresh.config.ts, main.ts, manifest.gen.ts, sdk/analytics.tsx
Remove preload from shelf;
Better analytics;
Ahead of time;
=> chore: improve analytics perf

components/ui/Popup.tsx
=> Style: Style on PopUp

components/product/ProductCard.tsx, components/product/ProductMatch.tsx, components/ui/PurchaseByCategory.tsx, components/ui/SectionDescription.tsx, components/ui/SectionHeader.tsx
=> Fix: Adjustment of the Website's HTML Structure

components/product/ProductDetails.tsx, components/ui/AvaliationSection.tsx, islands/PrincipalImages.tsx
=> Fix: Solving Problems in margins

components/product/ProductShelf.tsx, components/search/SearchResult.tsx, components/ui/InfoSection.tsx, components/ui/PageSection.tsx, components/ui/PurchaseByCategory.tsx, components/ui/SectionDescription.tsx, components/ui/SuggestionBanners.tsx, islands/SectionDescription.tsx
=> Fix: Spacing Adjustments

components/product/ProductShelf.tsx, components/search/SearchResult.tsx, components/ui/InfoSection.tsx, components/ui/PageSection.tsx, components/ui/SectionDescription.tsx, components/ui/SuggestionBanners.tsx, islands/ProductDescription.tsx
=> Fix: Spacing Adjustments pt2

components/ui/SectionDescription.tsx
=> Adjustments in SectionDescription

components/header/NavItem.tsx, components/product/ProductMatch.tsx, components/ui/PurchaseByCategory.tsx
=> Fix: Fixing Header

components/header/Alert.tsx, components/header/Drawers.tsx, components/header/NavItem.tsx, components/ui/SuggestionBanners.tsx
=> Fix: Adjustment in NavItem

components/ui/PurchaseByCategory.tsx
=> Feat: Added Dots in Mobile on PurchaseByCategory

components/ui/LPCategoryCards.tsx, sections/Content/LPCategoryCards.tsx
=> Feat (LP): Added Section LPCategoryCards in LP Black Friday

components/product/ProductCard.tsx
=> Fix: Fixing ProductCard

components/ui/ShippingSimulation.tsx
=> Fix: Fixing Max-Width in ShippingSimulation.tsx

components/ui/InfoSection.tsx
=> Feat: Implement Slider in InfoSection

components/product/ProductMatch.tsx
Alterando a Largura e Altura da Section ProductMatch
=> Fix: Changing Width and Height of Section ProductMatch

components/header/Buttons/Cart/common.tsx, components/header/LoginHeader.tsx, components/ui/SuggestionBanners.tsx, deno.json, fresh.gen.ts
Apps versions updated on this PR
=> chore: versions update

components/product/ProductCard.tsx, islands/ProductCardInfo.tsx, islands/SkuSelector.tsx, sections/Miscellaneous/Mailbiz.tsx
This refactoring aims to reduce the number of islands on the site, improving its performance.
=> refactor: site improved

components/header/Menu.tsx
=> Fix: Adjustment in Section Menu

components/header/Menu.tsx
Adicionando Hover na Section Menu
=> Refactor: Adding Hover in Section Menu

components/header/Header.tsx, components/header/Navbar.tsx, deno.json, fresh.config.ts, sections/Header/Header.tsx
this PR targets bump versions and using ctx device
=> perf: bump versions and using ctx device

islands/ProductCardInfo.tsx
Fixing in color ProductCardInfo
=> Fix: Fixing in color ProductCardInfo

components/header/Drawers.tsx, components/minicart/common/Cart.tsx, components/minicart/common/Installment.tsx
This PR aims to add Installment component to Minicart like this:
=> feat: adding Installment component to Minicart

components/search/Controls.tsx, components/wishlist/WishlistButton.tsx, deno.json
This PR aims to update libs versions for our web application.
=> chore: bump versions

components/product/ProductDetails.tsx, components/ui/ShareButton.tsx
This PR aims to add a new feature which shares the current url
=> feat: share button feature added
